### ISSUE TITLE
Show contents of README.md on Dockerhub

### ISSUE THREAD

**Issue by PatrickKa** [SpaceTeam/STS1_COBC_Docker#14]
I thought that this is done automatically, but apparently not.

Our README file is not very comprehensive, but it's still better than nothing. Also, we can always expand the README later.

**Comment by jeromehue** [comment]
https://github.com/marketplace/actions/docker-hub-description might be what we need.

**Comment by PatrickKa** [comment]
Seems like it didn't work: https://github.com/SpaceTeam/STS1_COBC_Docker/actions/runs/5148240264. I think you need to replace `repository: peterevans/dockerhub-description` with `repository: tuwienspaceteam/sts1-cobc`.
