### ISSUE TITLE
Make calling `docker run` more convenient

### ISSUE THREAD

**Issue by PatrickKa** [SpaceTeam/STS1_COBC_Docker#7]
### Description

To build the COBC SW with Docker, one currently has to execute something like the following from the top-level project directory:

~~~shell
docker run -it -v $(pwd):/project tuwienspaceteam/sts1-cobc:latest-linux-x86 bash -c "cd /project && cmake --preset=dev-linux-x86 && cmake --build --preset=dev-linux-x86"
~~~

By setting the default entrypoint of the container to Bash and the working directory to `/project` one ends up with a call that is at least a bit more convenient:

~~~shell
docker run -it -v $(pwd):/project tuwienspaceteam/sts1-cobc:latest-linux-x86 cmake --preset=dev-linux-x86 && cmake --build --preset=dev-linux-x86
~~~

In combination with an alias, it is even more convenient.

~~~shell
alias dr-sts1-linux="docker run -it -v $(pwd):/project tuwienspaceteam/sts1-cobc:latest-linux-x86"
dr-sts1-linux cmake --preset=dev-linux-x86
dr-sts1-linux cmake --build --preset=dev-linux-x86
~~~

Admittedly, something similar would have also been possible with the original command, but I think it would have been a bit more cumbersome.

Note that @jeromehue originally suggested `/app` as the current working directory. I changed it to `/project` because I think that name is more fitting. I don't know a lot about conventions for directory names on Linux, though, so if `/app` is the standard directory for stuff like this and what Linux users would expect, then that's completely fine with me. Something like `/usr/src/project` might also be worth considering.

### To do

- [ ] Make Bash the default entrypoint
- [ ] Set the default working directory to `/project` (or whatever the "best" choice is for this)

**Comment by PatrickKa** [comment]
From Slack conversation with @jeromehue

> Also for the working directory, I think it can be passed as an argument to docker run (https://docs.docker.com/engine/reference/run/#workdir)  which I prefer to trying to set it in the entry point command.
It should looks like this :
alias dr-sts1-linux="docker run -it -v $(pwd):/project tuwienspaceteam/sts1-cobc:latest-linux-x86 -w /project

**Comment by jeromehue** [comment]
```
alias dr-sts1-linux="docker run -it -v $(pwd):/project -w="/project" tuwienspaceteam/sts1-cobc:latest-linux-x86"
dr-sts1-linux cmake --preset=ci-linux-x86
dr-sts1-linux cmake --build --preset=dev-linux-x86
```

Using the ci preset is important for both linux/cobc
For Linux is used make instead of Ninja, and ninja is not installed yet.
For Cobc it has the correct path for stm32f411.
